engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    config:
      rule-sets: "phpmd.xml"
  scss-lint:
    enabled: true
ratings:
  paths:
  - src/**
  - resources/**
  - "**.php"
  - "**.js"
  - "**.scss"
exclude_paths:
- public/**/*
