engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - src/**
  - resources/**
  - "**.php"
  - "**.js"
  - "**.scss"
exclude_paths:
- public/**/*
exclude-exts=.min.css
ignore=adjoining-classes,box-model,ids,order-alphabetical,unqualified-attributes